### ISSUE TITLE
can we sync to the neuro_data twitter account?

### ISSUE THREAD

**Issue by jovo** [neurostorm/neurostorm.github.io#1]
so when we generate a new post, it automatically tweets?

**Comment by gkiar** [comment]
http://matthewpalmer.net/blog/2013/11/13/automatic-tweet-jekyll-post/

I use IFTTT for other things, love it. I'll sign up for an acct with admin@neurodata.io and set this up with my twitter first to ensure it works, then will get login info for ours and transfer the setup. Should be trivial.

**Comment by jovo** [comment]
Nice
